[package]
name = "egg-math-benchmark"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
egg.workspace = true
egglog-reports.workspace = true
num-rational.workspace = true
serde_json.workspace = true

[dev-dependencies]
egglog-experimental = { path = "../egglog-experimental", default-features = false }
